project_name: changemonitor
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ordspilleren/{{.ProjectName}}:latest"
      - "ordspilleren/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile
